import parse, {parseQueryArgs} from './parse';
import transpile from './transpile';

import type {CustomRules} from './converters/types';

export const description = `
"""
This file was generated by cf-graphql-schema-generator which was forked from
https://github.com/prisma-korea/graphql-schema-generator.

Do not make changes to this file directly.
Read more about in https://github.com/edwinbrowwn/cf-graphql-schema-generator.
"""
`;
export type Config = {
  customRules?: CustomRules;
  [key: string]: any;
};

const generateGraphqlSchema = async (
  source: string,
  config: Config,
): Promise<string> => {
  const model = await parse(source);
  const queryArgs = parseQueryArgs(source);

  const {createCRUD, format, ...rest} = config;

  const graphqlSchema =
    createCRUD === 'true'
      ? transpile(
          model,
          {
            ...rest,
            createQuery: 'true',
            createMutation: 'true',
          },
          queryArgs,
        )
      : transpile(model, {
          ...rest,
          createQuery: 'false',
          createMutation: 'false',
        });

  if (format === 'ts')
    return `\`${description}\`\nexport const schema = \` ${graphqlSchema}\` \nexport default schema;`;

  return description + graphqlSchema;
};

export default generateGraphqlSchema;
